- name: Build the docker image
  become: true
  shell: 
    cmd: docker build -t {{ dockerImageName }} .
    chdir: /volumes/docker/run/{{ dockerContainerName }}/build/
  when: isImageExists.stdout == 'false'