---
- name: Ensure non-prompt variables are defined
  assert:
    that:
      - param_action is defined
    fail_msg: "Mandatory variables not set"
  
- name: Call action task file
  include_tasks: "{{ param_action }}.yml"